// <auto-generated />
using System;
using Ik_Bitirme.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ik_Bitirme.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240628181235_inits")]
    partial class inits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.AdvanceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AdvanceRequests");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeesCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MersisNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxAdministration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("YearOfEstablishment")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId");

                    b.ToTable("Companys");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Address = "Ankara",
                            ContractEndDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(329),
                            ContractStartDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(328),
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(326),
                            Email = "abc@company.com",
                            MersisNo = "123456789",
                            Name = "Firma1",
                            PhoneNumber = "123456789",
                            Status = 1,
                            TaxAdministration = "vergiDariresi",
                            TaxNo = "123456789",
                            Title = "ltd",
                            YearOfEstablishment = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(330)
                        },
                        new
                        {
                            CompanyId = 2,
                            Address = "Ankara",
                            ContractEndDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(333),
                            ContractStartDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(332),
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(331),
                            Email = "scd@company.com",
                            MersisNo = "123456789",
                            Name = "Firma2",
                            PhoneNumber = "123456789",
                            Status = 1,
                            TaxAdministration = "vergiDariresi",
                            TaxNo = "123456789",
                            Title = "ltd",
                            YearOfEstablishment = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(334)
                        },
                        new
                        {
                            CompanyId = 3,
                            Address = "Ankara",
                            ContractEndDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(336),
                            ContractStartDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(336),
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(335),
                            Email = "dxs@company.com",
                            MersisNo = "123456789",
                            Name = "Firma3",
                            PhoneNumber = "123456789",
                            Status = 1,
                            TaxAdministration = "vergiDariresi",
                            TaxNo = "123456789",
                            Title = "ltd",
                            YearOfEstablishment = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(337)
                        },
                        new
                        {
                            CompanyId = 4,
                            Address = "İstanbul",
                            ContractEndDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(339),
                            ContractStartDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(339),
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(338),
                            Email = "qwe@company.com",
                            MersisNo = "123456789",
                            Name = "Firma4",
                            PhoneNumber = "123456789",
                            Status = 1,
                            TaxAdministration = "vergiDariresi",
                            TaxNo = "123456789",
                            Title = "ltd",
                            YearOfEstablishment = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(340)
                        },
                        new
                        {
                            CompanyId = 5,
                            Address = "İstanbul",
                            ContractEndDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(343),
                            ContractStartDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(342),
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(341),
                            Email = "rxa@company.com",
                            MersisNo = "123456789",
                            Name = "Firma5",
                            PhoneNumber = "123456789",
                            Status = 1,
                            TaxAdministration = "vergiDariresi",
                            TaxNo = "123456789",
                            Title = "ltd",
                            YearOfEstablishment = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(344)
                        });
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"), 1L, 1);

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(307),
                            Name = "Information Technology",
                            Status = 0
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(308),
                            Name = "Human Resources",
                            Status = 0
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(309),
                            Name = "Accounting",
                            Status = 0
                        },
                        new
                        {
                            DepartmentId = 4,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(310),
                            Name = "Marketing",
                            Status = 0
                        },
                        new
                        {
                            DepartmentId = 5,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(311),
                            Name = "Sales",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.ExpenseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ExpenseRequests");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(357),
                            Description = "Developing software applications for various platforms.",
                            Name = "Software Developer",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(359),
                            Description = "Analyzing and interpreting complex data sets to provide insights.",
                            Name = "Data Analyst",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(360),
                            Description = "Overseeing project timelines, resources, and deliverables.",
                            Name = "Project Manager",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(361),
                            Description = "Creating and executing marketing campaigns to promote products.",
                            Name = "Marketing Specialist",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 230, DateTimeKind.Local).AddTicks(362),
                            Description = "Assisting customers with product inquiries and issue resolution.",
                            Name = "Customer Support Representative",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "Employee",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = "Director",
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "Director",
                            NormalizedName = "DIRECTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "Admin"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "Employee"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.AppUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TcIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobId");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("Ik_Bitirme.Domain.Entities.AppUser");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0175655-8332-4700-ae81-386e4f12e533",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEFnBIcOYGpHz9SvmsMFNn7O+ZpJ2CDrzKWU0QraaRwiXt+yfin9yINjTq3yr+DDFJg==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a878e97-8f3c-4cb8-abd9-58f3ec05a4cc",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            Address = "abc",
                            BirthDate = new DateTime(2024, 6, 28, 21, 12, 35, 228, DateTimeKind.Local).AddTicks(8338),
                            BirthPlace = "aaa",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            FirstName = "admin",
                            HireDate = new DateTime(2024, 6, 28, 21, 12, 35, 228, DateTimeKind.Local).AddTicks(8340),
                            JobId = 1,
                            LastName = "admin",
                            Salary = 123m,
                            Status = 0,
                            TcIdentity = "123123"
                        });
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Director", b =>
                {
                    b.HasBaseType("Ik_Bitirme.Domain.Entities.AppUser");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("Director");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Employee", b =>
                {
                    b.HasBaseType("Ik_Bitirme.Domain.Entities.AppUser");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("Employee_CompanyId");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("Employee");

                    b.HasData(
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ac8c8de3-4fe9-46b2-8cae-b4d992c84e84",
                            Email = "ahmet@ahmet.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMET@EXAMPLE.COM",
                            NormalizedUserName = "AHMET",
                            PasswordHash = "AQAAAAEAACcQAAAAEO9llzzQLthqMWTS2hNOmCLxxhobcJzONlAulYUQnzk1xTBhRm1qnAMPwoBg5ImBxw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "34acba89-3c6d-46d5-8016-099d4644726f",
                            TwoFactorEnabled = false,
                            UserName = "ahmet",
                            Address = "abc",
                            BirthDate = new DateTime(2024, 6, 28, 21, 12, 35, 231, DateTimeKind.Local).AddTicks(2419),
                            BirthPlace = "aaa",
                            CreateDate = new DateTime(2024, 6, 28, 21, 12, 35, 231, DateTimeKind.Local).AddTicks(2418),
                            DepartmentId = 1,
                            FirstName = "sagasg",
                            HireDate = new DateTime(2024, 6, 28, 21, 12, 35, 231, DateTimeKind.Local).AddTicks(2420),
                            JobId = 1,
                            LastName = "asgsag",
                            Salary = 123m,
                            Status = 1,
                            TcIdentity = "123123",
                            CompanyId = 1
                        });
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.AdvanceRequest", b =>
                {
                    b.HasOne("Ik_Bitirme.Domain.Entities.Employee", "Employee")
                        .WithMany("Advances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Department", b =>
                {
                    b.HasOne("Ik_Bitirme.Domain.Entities.Company", null)
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.ExpenseRequest", b =>
                {
                    b.HasOne("Ik_Bitirme.Domain.Entities.Employee", "Employee")
                        .WithMany("Expenses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("Ik_Bitirme.Domain.Entities.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Ik_Bitirme.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Ik_Bitirme.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.Navigation("Department");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Director", b =>
                {
                    b.HasOne("Ik_Bitirme.Domain.Entities.Company", "Company")
                        .WithMany("Directors")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Ik_Bitirme.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Company", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Directors");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Ik_Bitirme.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Advances");

                    b.Navigation("Expenses");

                    b.Navigation("Leaves");
                });
#pragma warning restore 612, 618
        }
    }
}
